### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Suzy1970** [mtimkovich/saved_posts#1]
I'm getting a "HTTP 403 Forbidden" server error sometimes after clicking on the Reddit "request for permission - allow button".

**Comment by mtimkovich** [comment]
It only happens sometimes?

**Comment by Suzy1970** [comment]
I think I figured out the issue - refresh the page in my browser (https://maxtimkovich.com/saved_posts/) and then clear my cache - seems to have fixed it so far! So should this be marked as closed?

**Comment by mtimkovich** [comment]
Nah, I'll keep it open in case I can ever figure out what's causing that. Glad it worked out though!
